#!/bin/bash
count=0
while IFS= read -r -d '' dir
do 
if [ "$dir" != "." -a "$dir" != "." ]
then
count=$((count+1))
fi
done < <(find . -mindepth 1 -type d -print0)
echo "Numberof directories and subdirectories: $count"
